[package]
name = "embedded-websocket"
version = "0.3.2"
authors = ["David Haig"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ninjasource/embedded-websockets.git"
description = "A lightweight websocket library for embedded systems (no_std)"
keywords = ["websockets", "websocket", "embedded", "no_std"]
categories = ["embedded", "no-std", "network-programming"]
readme = "README.md"

[dependencies]
sha1 = "0.6"
heapless = "0.5"
byteorder = { version = "1.3", default-features = false }
httparse = { version = "1.3", default-features = false }
rand_core = "0.5"

[dev-dependencies]
rand = "0.7.3"
rustls = "0.19"
webpki = "*"
webpki-roots = "*"
